libraries:
  Filme:
    metadata_path:
      - metadata/movies/metadata.yml
      - metadata/movies/overlays.yml
      - metadata/movies/anime.yml
      - metadata/movies/serien.yml
      - metadata/movies/admin.yml
      - metadata/movies/Filme.yml
      - metadata/movies/People.yml
      # - metadata/movies/Genres.yml
      - metadata/movies/Countries.yml
      - metadata/movies/Awards.yml
      - metadata/movies/Decades.yml
      - metadata/movies/Suggestions.yml
    settings:
      asset_directory:
        - assets/movies/collections
        - assets/movies/filme
        - assets/movies/people
        # - assets/movies/genres
        - assets/movies/countries
        - assets/movies/awards
        - assets/movies/decades
        - assets/movies/suggestions
    operations:
      split_duplicates: true
      tmdb_collections:
        remove_suffix:
          - Filmreihe
          - Collection
        exclude_ids:
          - 290973
          - 9485
          - 115575
          - 163902
          - 34055
          - 661025
          - 661026
          - 661028
          - 661029
          - 661031
          - 304
          - 87359
          - 2344
          - 608101
          - 115838
          - 386382
          - 809185
          - 135483
          - 1565
          - 115762
          - 785583
          - 91361
          - 645
          - 328
          - 1575
          - 528
          - 748
          - 535313
        template:
          minimum_items: 2
          tmdb_collection_details: <<collection_id>>
          sort_title: <<collection_name>>
  Anime:
    metadata_path:
      - metadata/anime/metadata.yml
      - metadata/anime/filme.yml
      - metadata/anime/admin.yml
      - metadata/anime/Anime.yml
    settings:
      asset_directory:
        - assets/anime/collections
        - assets/anime/anime
  Serien:
    metadata_path:
      - metadata/shows/metadata.yml
      - metadata/shows/overlays.yml
      - metadata/shows/filme.yml
      - metadata/shows/admin.yml
      - metadata/shows/Serien.yml
    settings:
      asset_directory:
        - assets/shows/collections
        - assets/shows/serien
settings:
  tvdb_language: default
  cache: true
  cache_expiration: 60
  run_again_delay: 2
  sync_mode: sync
  show_unmanaged: true
  show_filtered: false
  show_missing: true
  save_missing: false
  asset_directory: assets
  asset_depth: 0
  asset_folders: true
  assets_for_all: true
  create_asset_folders: false
  show_missing_assets: true
  show_missing_season_assets: true
  minimum_items: 1
  missing_only_released: true
  delete_below_minimum: true
  only_filter_missing: false
  delete_not_scheduled: false
  ignore_ids:
  ignore_imdb_ids:
  dimensional_asset_rename: false
  show_options: false
  playlist_sync_to_user: all
  download_url_assets: false
  default_collection_order:
  verify_ssl: true
plex:
  url: <url>
  token: <token>
  timeout: 60
  clean_bundles: true
  empty_trash: true
  optimize: false
tmdb:
  apikey: <apikey>
  language: de
