libraries:
  Movies:
settings:
  cache: true
  cache_expiration: 60
  asset_directory:
    - //config/assets
  asset_folders: true
  create_asset_folders: false
  show_missing_season_assets: false
  sync_mode: append
  collection_minimum: 1
  delete_below_minimum: false
  delete_not_scheduled: false
  run_again_delay: 0
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_missing: true
  show_missing_assets: true
  save_missing: true
  tvdb_language: default
  ignore_ids:
  ignore_imdb_ids:
  asset_depth: 0
  dimensional_asset_rename: false
  show_options: false
  playlist_sync_to_user: all
plex:
  url: ####
  token: ####
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:
  apikey: ####
  language: en
tautulli:
  url: ####
  apikey: ####
radarr:
  url: ####
  token: ####
  add: false
  root_folder_path: ####
  monitor: true
  availability: ####
  quality_profile: ####
  tag: pmm
  search: true
  add_existing: false
  radarr_path:
  plex_path:
trakt:
  client_id: ####
  client_secret: #####
