libraries:
  Movies:
    metadata_path:
      - metadata/movies/metadata.yml
      - metadata/movies/admin.yml
      - metadata/movies/overlays4k.yml
      - metadata/movies/Movies.yml
    settings:
      asset_directory:
        - assets/movies/collections
        - assets/movies/filme
    operations:
      tmdb_collections:
        remove_suffix:
          - Filmreihe
          - Collection
        exclude_ids:
          - 304
        template:
          minimum_items: 2
          tmdb_collection_details: <<collection_id>>
          sort_title: <<collection_name>>
settings:
  tvdb_language: default
  cache: true
  cache_expiration: 60
  run_again_delay: 2
  sync_mode: sync
  show_unmanaged: true
  show_filtered: false
  show_missing: true
  save_missing: false
  asset_directory: assets
  asset_depth: 0
  asset_folders: true
  assets_for_all: true
  create_asset_folders: false
  show_missing_assets: true
  show_missing_season_assets: true
  missing_only_released: true
  delete_below_minimum: true
  minimum_items: 1
  only_filter_missing: false
  delete_not_scheduled: false
  ignore_ids:
  ignore_imdb_ids:
  show_options: false
  dimensional_asset_rename: false
  playlist_sync_to_user: all
  default_collection_order:
  download_url_assets: false
  verify_ssl: true
plex:
  url: <url>
  token: <token>
  timeout: 60
  clean_bundles: true
  empty_trash: true
  optimize: false
tmdb:
  apikey: <apikey>
  language: de
